import {
  alphard,
  carmy,
  fortuner,
  innova,
  innovaZenix,
  lexus,
  terios,
  toyotaYaris,
} from "@/assets";

export const vehicles = [
  {
    image: toyotaYaris,
    brand: "Toyota Yaris",
    type: "Hatchback",
    transmission: "Automatic/Manual",
    place: 3,
    bags: 1,
    star: 4.7,
    price: "$70",
  },
  {
    image: alphard,
    brand: "Alphard",
    type: "Minivan",
    transmission: "Automatic",
    place: 5,
    bags: 2,
    star: 4.8,
    price: "$95",
  },
  {
    image: lexus,
    brand: "Lexus NX - 300",
    type: "SUV",
    transmission: "Automatic",
    place: 3,
    bags: 2,
    star: 4.7,
    price: "$88",
  },
  {
    image: carmy,
    brand: "Camry",
    type: "Sedan",
    transmission: "Automatic",
    place: 3,
    bags: 2,
    star: 4.9,
    price: "$50",
  },
  {
    image: innova,
    brand: "Innova",
    type: "Minivan",
    transmission: "Manual",
    place: 5,
    bags: 2,
    star: 4.9,
    price: "$85",
  },
  {
    image: fortuner,
    brand: "Toyota Fortuner",
    type: "SUV",
    transmission: "Automatic",
    place: 5,
    bags: 2,
    star: 4.8,
    price: "$75",
  },
  {
    image: innovaZenix,
    brand: "Innova Zenix",
    type: "MPV",
    transmission: "Automatic/Manual",
    place: 6,
    bags: 2,
    star: 4.8,
    price: "$60",
  },
  {
    image: terios,
    brand: "Terios",
    type: "SUV",
    transmission: "Automatic/Manual",
    place: 5,
    bags: 2,
    star: 4.6,
    price: "$70",
  },
];

export const popularCars = [
  "Car Rental in Bandung",
  "Car Rental in Jakarta",
  "Car Rental in Bali",
  "Car Rental in Sydney",
  "Car Rental in New York",
  "Car Rental in Seoul",
  "Car Rental in Tokyo",
  "Car Rental in Paris",
  "Car Rental in Jeju Island",
  "Car Rental in Los Angeles",
  "Car Rental in Berlin",
  "Car Rental in Munich",
  "Car Rental in Yogyakarta",
  "Car Rental in Liverpool",
  "Car Rental in Glasglow",
  "Car Rental in Birmingham",
];
